production:
  host: localhost
  database: db_name
  username: db_user
  password: 'db_pass'
staging:
  host: "<%= ENV['WP_LOCAL_DB_HOST'] %>"
  database: "<%= ENV['WP_LOCAL_DB_NAME'] %>"
  username: "<%= ENV['WP_LOCAL_DB_USER'] %>"
  password: "<%= ENV['WP_LOCAL_DB_PASSWORD'] %>"
local:
  host: "<%= ENV['WP_LOCAL_DB_HOST'] %>"
  database: "<%= ENV['WP_LOCAL_DB_NAME'] %>"
  username: "<%= ENV['WP_LOCAL_DB_USER'] %>"
  password: "<%= ENV['WP_LOCAL_DB_PASSWORD'] %>"